services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file:
      - ./postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
  funnybot:
    container_name: funnybot
    image: funnybot
    build: funnybot_rs
    restart: always
    env_file:
      - ./funnybot_rs/.env
    depends_on:
      - postgres
volumes:
  postgres_data:
